services:
  - type: web
    name: jurist-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
